### ISSUE TITLE
empty tree

### ISSUE THREAD

**Issue by agenteo** [shageman/cobradeps#5]
Hi,

I tested this (0.1.1) with my cbra app today and I get an empty graph:

```
$ cobradeps
APP


DEPENDENCIES


 ALL PARTS
```

Here's a little background about the app: I am using the

```
path 'components' do
end
```

directive, and I also have a bundle group wrapping it.

**Comment by shageman** [comment]
This is fixed by 6470887e1b41a3eeb0d96d9d4dcd2221faf0dfa7 and gem version 0.2.1
